// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrzGAnZaCUOLg8CnSi6epXJpIiJeI7AE',
    appId: '1:584876907679:web:d5bbe265ff8caae277d6aa',
    messagingSenderId: '584876907679',
    projectId: 'firestorerecord',
    authDomain: 'firestorerecord.firebaseapp.com',
    storageBucket: 'firestorerecord.appspot.com',
    measurementId: 'G-9FYHJ5745D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeVPBffdMk0SVloyxKNt9ERcJdzzKN22s',
    appId: '1:584876907679:android:971a5172e88a1bb677d6aa',
    messagingSenderId: '584876907679',
    projectId: 'firestorerecord',
    storageBucket: 'firestorerecord.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNEi7BSASJY1JdPj35ynDjBFaHm0nw4uk',
    appId: '1:584876907679:ios:fb19453f971c025777d6aa',
    messagingSenderId: '584876907679',
    projectId: 'firestorerecord',
    storageBucket: 'firestorerecord.appspot.com',
    iosBundleId: 'com.example.firestoreRecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNEi7BSASJY1JdPj35ynDjBFaHm0nw4uk',
    appId: '1:584876907679:ios:fb19453f971c025777d6aa',
    messagingSenderId: '584876907679',
    projectId: 'firestorerecord',
    storageBucket: 'firestorerecord.appspot.com',
    iosBundleId: 'com.example.firestoreRecord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTrzGAnZaCUOLg8CnSi6epXJpIiJeI7AE',
    appId: '1:584876907679:web:9e0770efb62351e377d6aa',
    messagingSenderId: '584876907679',
    projectId: 'firestorerecord',
    authDomain: 'firestorerecord.firebaseapp.com',
    storageBucket: 'firestorerecord.appspot.com',
    measurementId: 'G-L8CBHRM1MH',
  );
}
